#include "privilege.h"
namespace GNET
{	
	static Operations __UNMEMBER_OPERATIONS []={
		_O_FACTION_TESTSYNC,
		_O_FACTION_CREATE,
		_O_FACTION_ACCELERATEEXPELSCHEDULE,
	}; 
	static Privilege __unmember_privilege(_R_UNMEMBER,__UNMEMBER_OPERATIONS,sizeof(__UNMEMBER_OPERATIONS)/sizeof(Operations));
	static Operations __SYSTEM_OPERATIONS []={
		_O_FACTION_CREATE,
		_O_FACTION_DEGRADE,
	}; 
	static Privilege __system_privilege(_R_SYSTEM,__SYSTEM_OPERATIONS,sizeof(__SYSTEM_OPERATIONS)/sizeof(Operations));
	static Operations __MASTER_OPERATIONS []={
		_O_FACTION_ACCEPTJOIN,
		_O_FACTION_EXPELMEMBER,
		_O_FACTION_APPOINT,
		_O_FACTION_MASTERRESIGN,
		_O_FACTION_BROADCAST,
		_O_FACTION_CHANGEPROCLAIM,
		_O_FACTION_UPGRADE,
		_O_FACTION_LEAVE,
		_O_FACTION_LISTMEMBER,
		_O_FACTION_RENAME,
		_O_FACTION_DISMISS,
		_O_FACTION_ALLIANCEAPPLY,
		_O_FACTION_ALLIANCEREPLY,
		_O_FACTION_HOSTILEAPPLY,
		_O_FACTION_HOSTILEREPLY,
		_O_FACTION_REMOVERELATIONAPPLY,
		_O_FACTION_REMOVERELATIONREPLY,
		_O_FACTION_LISTRELATION,
		_O_FACTION_CANCELEXPELSCHEDULE,
		_O_FACTION_FACTIONRENAME,
	}; 
	static Privilege __master_privilege(_R_MASTER,__MASTER_OPERATIONS,sizeof(__MASTER_OPERATIONS)/sizeof(Operations));
	static Operations __VICEMASTER_OPERATIONS []={
		_O_FACTION_ACCEPTJOIN,
		_O_FACTION_EXPELMEMBER,
		_O_FACTION_APPOINT,
		_O_FACTION_BROADCAST,
		_O_FACTION_RESIGN,
		_O_FACTION_CHANGEPROCLAIM,
		_O_FACTION_LEAVE,
		_O_FACTION_LISTMEMBER,
		_O_FACTION_RENAME,
		_O_FACTION_ALLIANCEAPPLY,
		_O_FACTION_ALLIANCEREPLY,
		_O_FACTION_HOSTILEAPPLY,
		_O_FACTION_HOSTILEREPLY,
		_O_FACTION_REMOVERELATIONAPPLY,
		_O_FACTION_REMOVERELATIONREPLY,
		_O_FACTION_LISTRELATION,
		_O_FACTION_CANCELEXPELSCHEDULE,
	}; 
	static Privilege __vicemaster_privilege(_R_VICEMASTER,__VICEMASTER_OPERATIONS,sizeof(__VICEMASTER_OPERATIONS)/sizeof(Operations));
	static Operations __BODYGUARD_OPERATIONS []={
		_O_FACTION_APPOINT,
		_O_FACTION_ACCEPTJOIN,
		_O_FACTION_RESIGN,
		_O_FACTION_LEAVE,
		_O_FACTION_LISTMEMBER,
		_O_FACTION_LISTRELATION,
	}; 
	static Privilege __bodyguard_privilege(_R_BODYGUARD,__BODYGUARD_OPERATIONS,sizeof(__BODYGUARD_OPERATIONS)/sizeof(Operations));
	static Operations __POINEER_OPERATIONS []={
		_O_FACTION_ACCEPTJOIN,
		_O_FACTION_RESIGN,
		_O_FACTION_LEAVE,
		_O_FACTION_LISTMEMBER,
		_O_FACTION_LISTRELATION,
	}; 
	static Privilege __poineer_privilege(_R_POINEER,__POINEER_OPERATIONS,sizeof(__POINEER_OPERATIONS)/sizeof(Operations));
	static Operations __MEMBER_OPERATIONS []={
		_O_FACTION_LEAVE,
		_O_FACTION_LISTMEMBER,
		_O_FACTION_LISTRELATION,
	}; 
	static Privilege __member_privilege(_R_MEMBER,__MEMBER_OPERATIONS,sizeof(__MEMBER_OPERATIONS)/sizeof(Operations));
}; //end of namespace	
