#ifndef _TASKCONST_H_
#define _TASKCONST_H_

enum{
	BACKGAME_ONLINE_REWARDING_TASK_ID			=	26191,	//	回归者上线奖励任务
	BACKGAME_INVITEE_MAIL_REWARDING_TASK_ID		=	33558,	//	邀请回归者的邮件奖励任务
	INVITE_BACKGAME_LEVEL_1_REWARDING_TASK_ID	=	26187,	//	邀请回归操作即时奖励任务（级别1）
	INVITE_BACKGAME_LEVEL_2_REWARDING_TASK_ID	=	26188,	//	邀请回归操作即时奖励任务（级别2）
	INVITE_BACKGAME_LEVEL_3_REWARDING_TASK_ID	=	26189,	//	邀请回归操作即时奖励任务（级别3）
};

#endif
