#ifndef __SKILL_STATEDEF_H__
#define __SKILL_STATEDEF_H__

namespace GNET
{
enum visible_state{
	// 通用状态
	VSTATE_BLESSED     = 1,  // 属性增强
	VSTATE_CURSED      = 2,  // 属性下降
	VSTATE_RETORT      = 3,  // 反震
	VSTATE_SLOW        = 4,  // 迟滞
	VSTATE_DIZZY       = 5,  // 昏迷
	VSTATE_SLEEP       = 6,  // 睡眠
	VSTATE_FIX         = 7,  // 定身
	VSTATE_SEALED      = 8,  // 封印, 不能攻击
	VSTATE_INFAUST     = 9,  // 受诅, 特殊不利状态
	VSTATE_THUNDER     = 10, // 雷击, 持续金系攻击
	VSTATE_TOXIC       = 11, // 中毒
	VSTATE_BURNING     = 12, // 燃烧, 持续火系攻击
	VSTATE_FALLEN      = 13, // 落石
	VSTATE_BLEEDING    = 14, // 放血
	VSTATE_MAGICLEAK   = 15, // 魔力燃烧
	VSTATE_ICEBLADE    = 16, // 霜刃
	VSTATE_POWERUP     = 17, // 爆气
	VSTATE_FIREBLADE   = 18, // 附加火伤害
	VSTATE_FLOWER1     = 19, // 鲜花1
	VSTATE_FLOWER2     = 20, // 鲜花2
	VSTATE_FLOWER3     = 21, // 鲜花3
	VSTATE_FLOWER4     = 22, // 鲜花4
	VSTATE_NOREGAIN    = 23, // 弱魂，自动恢复停止
	// 法师特有
	VSTATE_FIRESHIELD  = 24, // 烈焰护甲
	VSTATE_ICESHIELD   = 25, // 寒冰护甲
	VSTATE_SOILSHIELD  = 26, // 磐石护甲
	VSTATE_ANTIWATER   = 27, // 避水诀
	// 羽灵特有
	VSTATE_FEATHERSHIELD = 28, // 羽盾
	// 羽芒特有
	VSTATE_WINGSHIELD  = 29, // 翼盾
	VSTATE_FIREARROW   = 30, // 烈焰之矢
	// 妖精特有
	VSTATE_JINGJI      = 31, // 荆棘阵
	VSTATE_FOXFORM     = 32, // 妖狐变
	// 怪物特有
	VSTATE_BLIND         = 33, // 目盲

	VSTATE_IMMUNESEALED = 34,	//免疫封印//lgc
	VSTATE_IMMUNESLEEP 	= 35,	//免疫睡眠
	VSTATE_IMMUNEFIRE 	= 36,	//火免疫
	VSTATE_IMMUNEWATER 	= 37,	//水免疫
	VSTATE_IMMUNEMETAL 	= 38,	//金免疫
	VSTATE_IMMUNEWOOD 	= 39,	//木免疫
	
	VSTATE_IMMUNESOIL 	= 40,	//土免疫
	VSTATE_WINDSHIELD  	= 41,	//风盾术
	VSTATE_AIRSTREAMLOCK= 42,	//气流锁
	VSTATE_WEAKELEMENT 	= 43,	//元素虚弱
	VSTATE_IMMUNEWEAK	= 44,	//伤害加深免疫
	VSTATE_BEFROZEN 	= 45,	//冻结
	VSTATE_VACUUM 		= 46,	//真空
	VSTATE_WATERFIREARMOR = 47,	//水火护甲
	
	VSTATE_FSSTAR 		= 48,	//法师之星
	VSTATE_INVINCIBLE 	= 49,	//无敌 //此值若改变，同时应更新 cgame/gs/invincible_filter.cpp
	VSTATE_APGENCONT 	= 50,	//持续增加元气
	VSTATE_APLEAKCONT 	= 51,	//持续降低元气
	VSTATE_ADDATTACKDEGREE 		= 52,	//攻击等级增加
	VSTATE_ADDDEFENCEDEGREE 	= 53,	//防御等级增加
	VSTATE_ABSORBPHYSICDAMAGE 	= 54,	//吸收物理伤害
	VSTATE_ABSORBMAGICDAMAGE 	= 55,	//吸收法术伤害
	
	VSTATE_IMMUNEBLOODING		= 56,	//流血免疫
	VSTATE_HARDENSKIN			= 57,	//坚壁
	VSTATE_INVISIBLE			= 58,	//隐身//此值若改变，同时应更新 cgame/gs/invisible_filter.cpp
	VSTATE_SOULRETORT			= 59,	//反弹之魂
	VSTATE_SOULSEALED			= 60,	//封印之魂
	VSTATE_SOULBEATBACK			= 61,	//反击之魂
	VSTATE_SOULSTUN				= 62,	//击晕之魂
	VSTATE_HURTWHENUSESKILL		= 63,	//使用技能时受伤害

	VSTATE_INCDEBUFFDODGE		= 64,	//状态躲闪
	VSTATE_INCDAMAGEDODGE		= 65,	//伤害躲闪
	VSTATE_ADJUSTATTACKDEFEND1	= 66,	//加攻减防
	VSTATE_ADJUSTATTACKDEFEND2	= 67,	//减攻加防
	VSTATE_DEEPICETHRUST		= 68,	//深度冰刺
	VSTATE_ATTACKATTACHSTATE1	= 69,	//攻击时附加状态攻击1
	VSTATE_ATTACKATTACHSTATE2	= 70,	//攻击时附加状态攻击2
	VSTATE_ATTACKATTACHSTATE3	= 71,	//攻击时附加状态攻击3

	VSTATE_BLADESHADOW			= 72,	//八方剑影
	VSTATE_CONSECRATION 		= 73,	//献祭
	VSTATE_POISIONSEED			= 74,	//毒眼
	VSTATE_HPGENSEED			= 75,	//回血种
	VSTATE_INCWOODWATERDEFENSE 	= 76,	//增加木水物防 
	VSTATE_SPECIALSLOW			= 77,	//特殊的减速
	VSTATE_TRANSPORTMPTOPET 	= 78,	//向自己的宠物传输mp
	VSTATE_FASTPRAYINCMAGIC 	= 79,	//加快吟唱增加法攻
	
	VSTATE_INCDEFENCESMITE 		= 80,	//增加物防暴击
	VSTATE_INCRESISTMAGIC 		= 81,	//增加法防法攻
	VSTATE_TRANSPORTDAMAGETOPET = 82,	//向施放者(宠物)传输伤害
	VSTATE_ABSORBDAMAGEINCDEFENSE = 83,	//吸伤害加物法防
	VSTATE_CHANCEOFREBIRTH		= 84,	//枯木逢春
	VSTATE_INCCOUNTEDSMITE		= 85,	//提升暴击(限生效次数)
	VSTATE_ATTACKATTACHSTATE4	= 86,	//攻击时附加状态攻击4
	VSTATE_SHURA1				= 87,	//修罗道
	VSTATE_SHURA2				= 88,	//修罗道
	VSTATE_SHURA3				= 89,	//修罗道
	VSTATE_SHURA4				= 90,	//修罗道
	VSTATE_POSITIONROLLBACK		= 91,
	VSTATE_HPROLLBACK			= 92,
	VSTATE_NOCHANGESELECT		= 93,
	VSTATE_HEALABSORB			= 94,
	VSTATE_REPELONNORMALATTACK	= 95,
	VSTATE_DECCRITRESISTANCE	= 96,
	VSTATE_TRANSMITSKILLATTACK	= 97,
	VSTATE_ADDITIONALATTACK		= 98,
	VSTATE_FORBIDBESELECTED		= 99,
	VSTATE_DELAYEARTHHURT		= 100,
	VSTATE_DIZZYINCHURT			= 101,
	VSTATE_SOULRETORT2			= 102,
	VSTATE_FIXONDAMAGE			= 103,
	VSTATE_INCATTACKONDAMAGE	= 104,
	VSTATE_REBIRTH2				= 105,
	VSTATE_HEALSTEAL			= 106,
	VSTATE_DROPMONEYONDEATH		= 107,
	VSTATE_INCATTACKRANGE		= 108,
	VSTATE_INVINCIBLE5			= 109,
	VSTATE_THUNDERFORM			= 110,
	VSTATE_BLADEAURA			= 111,
	VSTATE_YJDANCE				= 112,
	VSTATE_FSICEWORLD			= 113,
	VSTATE_FLAGER				= 114,	//国战旗手
	VSTATE_DOG					= 115,
	VSTATE_SNAKE				= 116,
	VSTATE_PALSY				= 117,	//瘫痪特殊表现
	VSTATE_MODIFYSPECSKILLPRAY	= 118,	
	VSTATE_INCSPECSKILLDAMAGE	= 119,	
	VSTATE_HEALSHIELD			= 120,
	VSTATE_INCFLYSPEED			= 121,
	VSTATE_MOVEPUNISH			= 122,
	VSTATE_STANDPUNISH			= 123,
	VSTATE_STANDPUNISH2			= 124,
	VSTATE_CHANTSHIELD			= 125,
	VSTATE_INTERVALPALSY		= 126,
	VSTATE_HUNTERSOUL			= 127,
	VSTATE_WHITE1				= 128,
	VSTATE_WHITE2				= 129,
	VSTATE_WHITE3				= 130,
	VSTATE_BLACK1				= 131,
	VSTATE_BLACK2				= 132,
	VSTATE_BLACK3				= 133,
	VSTATE_WHITE1BLACK1			= 134,
	VSTATE_WHITE1BLACK2			= 135,
	VSTATE_WHITE2BLACK1			= 136,
	VSTATE_INTERNALINJURY		= 137,
	VSTATE_DEATHRESETCD			= 138,
	VSTATE_APPENDDAMAGE			= 139,
	VSTATE_COOLDOWNPUNISH		= 140,
	VSTATE_SKILL2772			= 141,
	VSTATE_DETAINDART           = 142,
    VSTATE_EXTRAEXPFACTOR       = 143,

	VSTATE_MAX = 192,
};

enum hidden_state{
	HSTATE_DIZZY         = 1,    // 昏迷
	HSTATE_SLEEP         = 2,    // 睡眠
	HSTATE_SLOW          = 3,    // 移动速度减慢
	HSTATE_RETORT        = 4,    // 反震物理伤害
	HSTATE_FEATHERSHIELD = 5,    // 羽盾

	HSTATE_FIRESHIELD    = 6,    // 烈焰护甲
	HSTATE_ICESHIELD     = 7,    // 寒冰护甲
	HSTATE_FIX           = 8,    // 定身
	HSTATE_SEALED        = 9,    // 不能攻击
	HSTATE_BLIND         = 10,   // 变被动

	HSTATE_SOILSHIELD    = 11,   // 磐石护甲
	HSTATE_THUNDER       = 12,   // 持续金伤害
	HSTATE_TOXIC         = 13,   // 持续木伤害(中毒)
	HSTATE_BURNING       = 14,   // 持续火伤害
	HSTATE_FALLEN        = 15,   // 持续土伤害

	HSTATE_MAGICLEAK     = 16,   // 持续减少MP
	HSTATE_BLEEDING      = 17,   // 持续物理伤害(放血)
	HSTATE_DECDEFENCE    = 18,   // 降低物理防御力
	HSTATE_DECRESIST     = 19,   // 降低五行防御力
	HSTATE_DECATTACK     = 20,   // 降低物理攻击力

	HSTATE_INCHURT       = 21,   // 自身伤害加倍
	HSTATE_SLOWATTACK    = 22,   // 攻击速度减慢
	HSTATE_SLOWPRAY      = 23,   // 减慢吟唱
	HSTATE_DECACCURACY   = 24,   // 准确度下降
	HSTATE_DECDODGE      = 25,   // 降低躲避率

	HSTATE_FASTHPGEN     = 26,   // HP恢复速度加快(主动)
	HSTATE_FASTMPGEN     = 27,   // MP恢复速度加快(主动)
	HSTATE_INCHP         = 28,   // 增加HP上限
	HSTATE_INCMP         = 29,   // 增加MP上限
	HSTATE_INCDEFENCE    = 30,   // 加强物理防御力

	HSTATE_INCRESIST     = 31,   // 增强五行防御力
	HSTATE_INCATTACK     = 32,   // 提高物理攻击力
	HSTATE_FASTATTACK    = 33,   // 攻击加速
	HSTATE_INCDODGE      = 34,   // 躲避率增加
	HSTATE_DECHURT       = 35,   // 自身伤害减半

	HSTATE_INCACCURACY   = 36,   // 准确度上升
	HSTATE_FASTPRAY      = 37,   // 加快吟唱
	HSTATE_ICEBLADE      = 38,   // 附加冰伤害
	HSTATE_FIREBLADE     = 39,   // 附加火伤害
	HSTATE_TOXICBLADE    = 40,   // 毒牙

	HSTATE_HPGEN         = 41,   // 持续恢复HP
	HSTATE_MPGEN         = 42,   // 持续恢复MP
	HSTATE_DECMAGIC      = 43,   // 法术攻击力降低
	HSTATE_SPEEDUP       = 44,   // 加速
	HSTATE_DECHP         = 45,   // 降低HP上限

	HSTATE_INCMAGIC      = 46,   // 增强魔法攻击力
	HSTATE_TIGERFORM     = 47,   // 白虎变
	HSTATE_ENHANCEGOLD   = 48,   // 金防上升
	HSTATE_ENHANCEWOOD   = 49,   // 木防上升
	HSTATE_ENHANCEWATER  = 50,   // 水防上升

	HSTATE_ENHANCEFIRE   = 51,   // 火防上升
	HSTATE_ENHANCESOIL   = 52,   // 土防上升
	HSTATE_REDUCEGOLD    = 53,   // 金防下降
	HSTATE_REDUCEWOOD    = 54,   // 木防下降
	HSTATE_REDUCEWATER   = 55,   // 水防下降

	HSTATE_REDUCEFIRE    = 56,   // 火防下降
	HSTATE_REDUCESOIL    = 57,   // 土防下降
	HSTATE_ANTIWATER     = 58,   // 避水诀
	HSTATE_PANRUO        = 59,   // 般若心经
	HSTATE_POWERUP       = 60,   // 真元爆发

	HSTATE_XISUI         = 61,   // 洗髓经
	HSTATE_YIJIN         = 62,   // 易筋经
	HSTATE_APGEN         = 63,   // 兽王之怒
	HSTATE_STONESKIN     = 64,   // 坚甲符
	HSTATE_IRONSHIELD    = 65,   // 金钟罩

	HSTATE_GIANT         = 66,   // 巨灵神力
	HSTATE_DEVILSTATE    = 67,   // 化血成魔
	HSTATE_BLESSMAGIC    = 68,   // 灵助符
	HSTATE_WINGSHIELD    = 69,   // 翼盾
	HSTATE_FIREARROW     = 70,   // 烈焰之矢

	HSTATE_EAGLECURSE    = 71,   // 狂雷天鹰
	HSTATE_FREEMOVE      = 72,   // 无视所有行动阻碍状态
	HSTATE_FROZEN        = 73,   // 持续冰伤害
	HSTATE_INCSMITE      = 74,   // 爆机率提升
	HSTATE_FOXFORM       = 75,   // 妖狐变
	HSTATE_INVINCIBLE    = 76,   // 无敌
	HSTATE_JINGJI        = 77,   // 荆棘阵
	HSTATE_NOREGAIN      = 78,   // 弱魂，自动恢复停止
	HSTATE_CANTI         = 79,   // 残体, 伤害增益
	HSTATE_APLEAK        = 80,   // 碎灵, 受到攻击失去元气
	HSTATE_SWIFTFORM     = 81,   // 飞花遁影
	HSTATE_FASTRIDE      = 82,   // 骑乘加速
	HSTATE_SHARPBLADE    = 83,   // 物理攻击提高
	HSTATE_IMMUNESEALED		= 84,	//免疫封印//lgc
	HSTATE_IMMUNESLEEP		= 85,	//免疫睡眠
	HSTATE_IMMUNESLOWDIZZY	= 86,	//免疫移动减速和晕
	
	HSTATE_IMMUNEWOUND		= 87,	//免疫按比例掉血
	HSTATE_IMMUNEALL		= 88,	//免疫所有负面状态
	HSTATE_IMMUNEPHYSICAL	= 89,	//免疫物理伤害
	HSTATE_IMMUNEFIRE		= 90,	//免疫火伤害
	HSTATE_IMMUNEWATER		= 91,	//免疫水伤害
	HSTATE_IMMUNEMETAL		= 92,	//免疫金伤害
	HSTATE_IMMUNEWOOD		= 93,	//免疫木伤害
	HSTATE_IMMUNESOIL		= 94,	//免疫土伤害
	HSTATE_IMMUNEMAGICAL	= 95,	//免疫五行伤害
	HSTATE_ARROGANT			= 96,	//免疫一切状态

	HSTATE_SLOWSWIM			= 97,	//游泳比例减速
	HSTATE_FASTSWIM			= 98,	//游泳比例加速
	HSTATE_SLOWFLY			= 99,	//飞行比例减速
	HSTATE_FASTFLY			= 100,	//飞行比例加速
	HSTATE_SLOWRIDE			= 101, 	//骑乘比例减速
	HSTATE_APGENCONT		= 102,	//持续增加元气
	HSTATE_APLEAKCONT		= 103, 	//持续减少元气
	HSTATE_INCELFSTR		= 104,	//增加小精灵力量
	HSTATE_INCELFAGI		= 105,	//增加小精灵敏捷
	HSTATE_INCDEFENCE2		= 106,	//增加物理防御
	
	HSTATE_WEAKELEMENT		= 107,	//元素虚弱，物理防御增加 法术防御下降
	HSTATE_DEEPPOISION 		= 108,	//深毒，受到伤害加深
	HSTATE_ROOTED			= 109,	//扎根，定身同时伤害减少同时反弹伤害
	HSTATE_EARTHGUARD		= 110,	//大地守护，回复hp伤害减少物理和法术攻击下降
	HSTATE_FURY				= 111,	//狂暴，目标防御和法术防御降低同时攻击等级增加
	HSTATE_SANDSTORM		= 112,	//沙暴，命中降低施法速度变慢
	HSTATE_HOMEFEELING		= 113,	//乡情，生命和真气回复速度增加移动速度增加
	HSTATE_REDUCEWATER2		= 114,	//湮灭，水防减低
	HSTATE_INCSMITE2		= 115, 	//幸运，暴击增加
	HSTATE_DECDEFENCE2		= 116,	//冲击，物理防御降低
	
	HSTATE_REDUCEFIRE2		= 117,	//火花，火防御降低
	HSTATE_SLOWATTACKPRAY	= 118,	//心火，物理和法术攻击速度下降
	HSTATE_BURNING2			= 119,	//火种，持续火伤害
	HSTATE_BURNINGFEET		= 120,	//燃足，火防御降低，移动速度降低
	HSTATE_HARDENSKIN		= 121,	//坚壁，吸收物理和法术伤害，降低自身移动速度
	HSTATE_REDUCEGOLD2		= 122,	//刃切，金防御降低
	HSTATE_LEAFDANCE		= 123,	//叶舞，迟缓+流血
	HSTATE_CHARRED			= 124,	//烧焦，防御下降攻击下降移动速度增加
	HSTATE_VACUUM			= 125,	//真空，施法速度变慢 移动变慢 受到伤害减少
	HSTATE_IMMUNEBLOODING	= 126,	//免疫流血
	
	HSTATE_ABSORBPHYSICDAMAGE	= 127,	//吸收物理伤害
	HSTATE_ABSORBMAGICDAMAGE	= 128,	//吸收法术伤害
	HSTATE_RETORTMAGIC		= 129,		//反弹法术伤害
	HSTATE_WINDSHIELD		= 130,		//风盾，伤害减少物理攻击速度和闪避提升
	HSTATE_AIRSTREAMLOCK	= 131,		//气流锁，目标定身且有几率被封印
	HSTATE_CLOSED			= 132,		//封闭，封印且物理免疫
	HSTATE_IMMUNEWEAK		= 133,		//免疫伤害加深
	HSTATE_BEFROZEN			= 134,		//冻结，同眩晕
	HSTATE_ADDATTACKDEGREE  = 135,		//增加攻击等级
	HSTATE_SUBATTACKDEGREE  = 136,		//降低攻击等级
	HSTATE_ADDDEFENCEDEGREE  = 137,		//增加防御等级
	HSTATE_SUBDEFENCEDEGREE  = 138,		//降低防御等级
	HSTATE_FALLEN2 			= 139, 		//持续土伤害，受攻防等级影响同burning2
	HSTATE_SEALED2			= 140,		//不能攻击2
	HSTATE_FIX2				= 141,		// 定身2
	HSTATE_DECHURT2			= 142,		// 物理伤害减半2
	HSTATE_INCHURT2			= 143,		// 物理伤害加倍2
	HSTATE_INCHP2			= 144,		// 增加HP最大值2，增量
	HSTATE_INCATTACK2		= 145,		// 增强攻击力2, 增加比率
	HSTATE_INCMAGIC2		= 146,		// 增强法术攻击力2, 增加比率
	HSTATE_FASTPRAY2		= 147,		// 吟唱加速2
	HSTATE_SPEEDUP2			= 148,		// 加速2， 增加比率
	HSTATE_INVISIBLE		= 149,		// 隐身 //此值若改变，同时应更新 cgame/gs/invisible_filter.cpp
	HSTATE_INCANTIINVISIBLEACTIVE = 150,// 增加反隐等级
	HSTATE_INCHPSTEAL		= 151,		// 增加吸血
	HSTATE_INCCRITDAMAGE	= 152,		// 增加爆击伤害
	HSTATE_INCDAMAGEDODGE	= 153,		// 增加伤害闪避
	HSTATE_INCDEBUFFDODGE	= 154,		// 增加状态闪避
	HSTATE_REBIRTH			= 155,		// 重生
	HSTATE_SOULRETORT		= 156,		// 反弹之魂
	HSTATE_SOULSEALED		= 157,		// 封印之魂
	HSTATE_SOULBEATBACK		= 158,		// 反击之魂
	HSTATE_SOULSTUN			= 159,		// 击晕之魂
	HSTATE_DEEPENBLESS		= 160,		// 祝福加深
	HSTATE_WEAKENBLESS		= 161,		// 祝福抑制
	HSTATE_HURTWHENUSESKILL	= 162,		// 使用技能时受伤害
	HSTATE_INTERRUPTWHENUSESKILL = 163, // 使用技能时被中断	
	HSTATE_FISHFORM			= 164,		// 鱼人变
	HSTATE_DEEPICETHRUST	= 165,		//深度冰刺
	HSTATE_ADJUSTATTACKDEFEND = 166,	//攻防等级调整
	HSTATE_INCHURTPHYSICGOLD= 167,		//物理金属性攻击伤害加深
	HSTATE_INCHURTWOODWATER = 168,		//木水属性攻击伤害加深
	HSTATE_INCHURTFIREEARTH = 169,		//火土属性攻击伤害加深
	HSTATE_ATTACKATTACHSTATE1 = 170,	//攻击时附加状态攻击1
	HSTATE_ATTACKATTACHSTATE2 = 171,	//攻击时附加状态攻击2
	HSTATE_ATTACKATTACHSTATE3 = 172,	//攻击时附加状态攻击3
	HSTATE_BEATTACKEDATTACHSTATE1 = 173,//被攻击时附带状态攻击1
	HSTATE_BEATTACKEDATTACHSTATE2 = 174,//被攻击时附带状态攻击2
	HSTATE_BEATTACKEDATTACHSTATE3 = 175,//被攻击时附带状态攻击3
	HSTATE_BLADESHADOW		= 176,		//八方剑影
	HSTATE_POISIONSEED		= 177,		//毒眼
	HSTATE_HPGENSEED		= 178,		//回血种
	HSTATE_INCWOODWATERDEFENSE = 179,	//增加木水物防 
	HSTATE_SPECIALSLOW		= 180,		//特殊的减速
	HSTATE_INCDEFENCESMITE 	= 181,		//增加物防暴击
	HSTATE_INCRESISTMAGIC 	= 182,		//增加法防法攻
	HSTATE_TRANSPORTMPTOPET = 183,		//向自己的宠物传输mp
	HSTATE_TRANSPORTDAMAGETOPET = 184,	//向施放者(宠物)传输伤害
	HSTATE_ABSORBDAMAGEINCDEFENSE = 185,	//吸伤害加物法防
	HSTATE_FASTPRAYINCMAGIC = 186,		//加快吟唱增加法攻
	HSTATE_INCREMENTALHPGEN = 187,		//渐增的回血
	HSTATE_CONSECRATION 	= 188,		//献祭
	HSTATE_CHANCEOFREBIRTH	= 189,		//枯木逢春
	HSTATE_SPECIALPHYSICHURTTRIGGER	= 190,	//特殊的物理伤害触发器
	HSTATE_INCCOUNTEDSMITE	= 191,		//提升暴击(限生效次数)
	HSTATE_ATTACKATTACHSTATE4 = 192,	//攻击时附加状态攻击4
	HSTATE_BEATTACKEDATTACHSTATE4 = 193,//被攻击时附带状态攻击4
	HSTATE_WEAPONDISABLED	= 194,		//武器失效
	HSTATE_INCAGGROONDAMAGE = 195,		//怪物增加受到伤害时的仇恨
	HSTATE_ENHANCESKILLDAMAGE = 196,	//增加技能对npc的伤害
	HSTATE_DETECTINVISIBLE	= 197,		//侦测周围隐身玩家
	HSTATE_FASTMPGEN2     	= 198,   	// MP恢复速度加快(主动)
	HSTATE_POSITIONROLLBACK	= 199,
	HSTATE_HPROLLBACK		= 200,
	HSTATE_NOFLY			= 201,
	HSTATE_NOCHANGESELECT	= 202,
	HSTATE_HEALABSORB		= 203,
	HSTATE_REPELONNORMALATTACK	= 204,
	HSTATE_INCCRITRESISTANCE	= 205,
	HSTATE_DECCRITRESISTANCE	= 206,
	HSTATE_TRANSMITSKILLATTACK	= 207,
	HSTATE_ADDITIONALHEAL		= 208,
	HSTATE_ADDITIONALATTACK		= 209,
	HSTATE_TRANSPORTDAMAGETOLEADER = 210,
	HSTATE_FORBIDBESELECTED		= 211,
	HSTATE_ENHANCESKILLDAMAGE2	= 212,
	HSTATE_DELAYEARTHHURT		= 213,
	HSTATE_DIZZYINCHURT			= 214,
	HSTATE_SOULRETORT2			= 215,
	HSTATE_FIXONDAMAGE			= 216,
	HSTATE_APGEN2				= 217,
	HSTATE_INCATTACK3			= 218,
	HSTATE_INCATTACKONDAMAGE	= 219,
	HSTATE_REBIRTH2				= 220,
	HSTATE_HEALSTEAL			= 221,
	HSTATE_DROPMONEYONDEATH		= 222,
	HSTATE_INCATTACKRANGE		= 223,
	HSTATE_INVINCIBLE5			= 224,
	HSTATE_THUNDERFORM			= 225,
	HSTATE_BLADEAURA			= 226,
	HSTATE_YJDANCE				= 227,
	HSTATE_DELAYTRANSMIT		= 228,
	HSTATE_DECNORMALATTACKHURT	= 229,
	HSTATE_INCATKDEFHP			= 230,
	HSTATE_HPMPGENNOTINCOMBAT	= 231,
	HSTATE_INCHPMP				= 232,
	HSTATE_INCHURT3				= 233,
	HSTATE_NONPENALTYPVP		= 234,
	HSTATE_INCRESIST2			= 235,
	HSTATE_FLAGER				= 236,	//国战旗手
	HSTATE_SUBDEFENCEDEGREE2 	= 237,	//降低防御等级2
	HSTATE_INCATKDEFHP2			= 238,
	HSTATE_INCSMITE3			= 239,
	HSTATE_INCPENRES			= 240,	//提升猎魔/御魔等级
	HSTATE_INCMAXHPATKDFDLEVEL	= 241,	//同时提升HP上限和攻防等级
	HSTATE_GTAWARD1				= 242, 	//gt奖励的buff1
	HSTATE_GTAWARD2				= 243, 	//gt奖励的buff2
	HSTATE_DECHURT3				= 244,	//伤害减免3
	HSTATE_ATTACHSTATETOSELF	= 245,	//给自己附加状态包
	HSTATE_ATTACHSTATETOTARGET	= 246,	//给目标附加状态包
	HSTATE_IMMUNEPHYSICAL2		= 247,	//免疫物理伤害2
	HSTATE_IMMUNEMETAL2			= 248,	//免疫金伤害2
	HSTATE_IMMUNEWOOD2			= 249,	//免疫木伤害2
	HSTATE_IMMUNEWATER2			= 250,	//免疫水伤害2
	HSTATE_IMMUNEFIRE2			= 251,	//免疫火伤害2
	HSTATE_IMMUNESOIL2			= 252,	//免疫土伤害2
	HSTATE_RETORT2				= 253,
	HSTATE_ADDATTACKDEFENDDEGREE= 254,
	HSTATE_PALSY				= 255,	//瘫痪特殊表现
	HSTATE_INCHURT4				= 256,
	HSTATE_INCBECRITRATE		= 257,
	HSTATE_MODIFYSPECSKILLPRAY	= 258,
	HSTATE_INCSPECSKILLDAMAGE	= 259,
	HSTATE_ICESHIELD2			= 260,
	HSTATE_FIRESHIELD2			= 261,
	HSTATE_HEALSHIELD			= 262,
	HSTATE_INCFLYSPEED			= 263,
	HSTATE_INCVIGOUR			= 264,
	HSTATE_INCVIGOUR2			= 265,
	HSTATE_MOVEPUNISH			= 266,
	HSTATE_STANDPUNISH			= 267,
	HSTATE_STANDPUNISH2			= 268,
	HSTATE_CHANTSHIELD			= 269,
	HSTATE_INTERVALPALSY		= 270,
	HSTATE_INTERNALINJURY		= 271,
	HSTATE_ATKDAMAGEREDUCE		= 272,
	HSTATE_DEATHRESETCD			= 273,
	HSTATE_APPENDENCHANT		= 274,
	HSTATE_APPENDDAMAGE			= 275,
	HSTATE_COOLDOWNAWARD		= 276,
	HSTATE_HUNTERSOUL			= 277,
    HSTATE_SHADOWFORM           = 278,
    HSTATE_FAIRYFORM            = 279,
    HSTATE_ADDFROSTEFFECT       = 280,
    HSTATE_MOONGOD              = 281,
    HSTATE_ENHANCESKILLDAMAGE3  = 282,
	HSTATE_CRITDAMAGEREDUCE		= 283,
    HSTATE_INCPHYSICALDAMAGE    = 284,
    HSTATE_INCMAGICALDAMAGE     = 285,
	HSTATE_INCHURT5				= 286,
	HSTATE_BLACKWHITE			= 287,
	HSTATE_COOLDOWNPUNISH		= 288,
	HSTATE_ANTICLEARBUF			= 289,
	HSTATE_INCENCHANTRANGE		= 290,
    HSTATE_INCPHYSICALMAGICALDEFENSE = 291,
    HSTATE_REDUCEGOLD3          = 292,
    HSTATE_REDUCEWATER3         = 293,
    HSTATE_GENHPAP              = 294,
	HSTATE_DETAINDART           = 295,
    HSTATE_EXTRAEXPFACTOR       = 296,
	HSTATE_WEAKENBLESS2			= 297,
	HSTATE_SOLO_INCATTACKANDMAGIC    = 298,
	HSTATE_SOLO_INCDEFENCE      = 299,
	HSTATE_SOLO_ENHANCERESIST   = 300,
	HSTATE_SOLO_INCMAXHP        = 301,
	HSTATE_SOLO_HPGEN           = 302,
	HSTATE_SOLO_DECHURT         = 303,
	HSTATE_SOLO_ADDATTACKRANGE  = 304,
	HSTATE_SOLO_INVINCIBLE      = 305,
	HSTATE_THUNDER3             = 306,
	HSTATE_TOXIC3               = 307,
	HSTATE_FLOOD3				= 308,
	HSTATE_BURNING3             = 309,
	HSTATE_FALLEN3				= 310,
	HSTATE_NEWBUFFSPEED			= 398,
};

#define IMMUNEPHYSICAL 0x00000001   //免疫物理攻击
#define IMMUNEMETAL    0x00000002   //免疫金系
#define IMMUNEWOOD     0x00000004   //免疫木系
#define IMMUNEWATER    0x00000008   //免疫水系
#define IMMUNEFIRE     0x00000010   //免疫火系
#define IMMUNESOIL     0x00000020   //免疫土系
#define IMMUNEDIZZY    0x00000040   //免疫昏迷
#define IMMUNESLEEP    0x00000080   //免疫睡眠
#define IMMUNESLOW     0x00000100   //免疫减速
#define IMMUNEFIX      0x00000200   //免疫定身
#define IMMUNECURSED   0x00000400   //免疫封印（不能攻击）
#define IMMUNEWEAK     0x00000800   //免疫伤害加倍
#define IMMUNEREPEL    0x00001000   //免疫击退
#define IMMUNEWOUND    0x00002000   //免疫HP上限下降，按比例减HP
#define IMMUNEBREAK    0x00004000   //免疫打断当前session
#define IMMUNEDIRECT   0x00008000   //免疫behurt
#define IMMUNECLEAR    0x00010000   //免疫清除filter
#define IMMUNEBLOODING 0x00020000	//免疫流血			lgc
#define IMMUNEALL	   0x00040000	//免疫所有负面状态
#define IMMUNEDROP	   0x00080000	//免疫掉落物品或金币
#define IMMUNEPALSY	   0x00100000   //免疫瘫痪

enum
{
	MULTIOBJ_EFFECT_HEAL,
	MULTIOBJ_EFFECT_ATTACK,
	MULTIOBJ_EFFECT_ATTACK2,
};

enum
{
	STIME_GFX_MOVEPUNISH = 1,
	STIME_GFX_INTERNALINJURY,
	STIME_GFX_HUNTERSOUL,
};

}

#endif
